version: '3.1'

services:
    openacs:
        image: sussdorff/openacs:oacs-5-10
        depends_on: 
            - postgres
        ports: 
            - 8080:8000
        environment:
            - NS_DEBUG=false
            - POSTGRES_PASSWORD=testing
            - NS_verboseSQL=false
            - NS_DEV=false
            - LANGUAGE
        
        healthcheck:
            test: ["CMD-SHELL", "wget -qO - http://localhost:8000/SYSTEM/openacs-test || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 2

    postgres:
        image: postgres:11-alpine
        environment: 
            - POSTGRES_PASSWORD=testing
            - POSTGRES_USER=openacs
            - POSTGRES_DB=openacs
        volumes:
            - db_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U openacs"]
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    db_data:
    